# Generated by Django 4.0.4 on 2022-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_contactmodel_rename_aboutpage_aboutmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
