# Generated by Django 4.0.4 on 2022-05-29 22:08

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_referencesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.filepath),
        ),
    ]
