# Generated by Django 4.0.4 on 2022-05-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_referencesmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
