# Generated by Django 4.0.4 on 2022-05-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_referencesmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencesmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
